#!/usr/bin/env node
/**
 * Ranks src/data/town_pipeline.json into CONTENT_QUEUE.md.
 *
 * Score = Hispanic population (thousands) x contractor density index.
 *
 * Rationale: raw Hispanic percentage over-ranks small towns (a 70%-Hispanic
 * town of 12,000 is a smaller opportunity than a 40%-Hispanic city of 90,000),
 * and raw population over-ranks big non-Latino places. Multiplying absolute
 * Hispanic population by trade-worker density ranks by the thing that actually
 * drives revenue here: how many Spanish-speaking contractors live there.
 *
 *   npm run queue
 */
import { readFile, writeFile } from 'node:fs/promises';

const pipeline = JSON.parse(await readFile('src/data/town_pipeline.json', 'utf8'));
const live = JSON.parse(await readFile('src/data/towns.json', 'utf8'));
const services = JSON.parse(await readFile('src/data/services.json', 'utf8'));

const liveSlugs = new Set(live.towns.map((t) => t.slug));
const pagesPerTown = services.services.length * 2;

const ranked = pipeline.candidates
  .filter((c) => !liveSlugs.has(c.slug))
  .map((c) => {
    const hispanicPop = Math.round(c.pop * (c.hispanic_pct / 100));
    return { ...c, hispanicPop, score: Math.round((hispanicPop / 1000) * c.contractor_index) };
  })
  .sort((a, b) => b.score - a.score)
  .slice(0, 30);

const tiers = [
  { name: 'Tier 1 — build next', slice: [0, 10] },
  { name: 'Tier 2 — build after Tier 1 ranks', slice: [10, 20] },
  { name: 'Tier 3 — build once the model is proven', slice: [20, 30] },
];

let md = `# Content queue — next 30 towns

Generated by \`npm run queue\` from \`src/data/town_pipeline.json\`. Do not edit by
hand; edit the data file and regenerate.

**Ranking method.** Score = Hispanic population (in thousands) × contractor
density index (1–10). Raw Hispanic *percentage* over-ranks small towns, and raw
population over-ranks large non-Latino ones. Multiplying absolute Hispanic
population by trade-worker density ranks by what actually drives revenue here:
how many Spanish-speaking contractors and small-business owners live there.

**Caveat on the numbers.** \`pop\` and \`hispanic_pct\` are approximate 2020 Census
/ ACS figures and NYC neighborhood estimates. \`contractor_index\` is currently a
judgment estimate, not measured data — replace it with ACS occupation data
(construction and extraction, installation/maintenance/repair) before treating
this ordering as final. The rank order is directionally sound; the exact scores
are not.

Each town promoted adds **${pagesPerTown} pages** (${services.services.length} services × 2 languages) plus a town hub.
All 30 → **${30 * pagesPerTown} pages**.

`;

for (const tier of tiers) {
  const rows = ranked.slice(...tier.slice);
  if (!rows.length) continue;
  md += `\n## ${tier.name}\n\n`;
  md += `| # | Town | County | State | Pop | Hisp % | Hisp. pop | Contractor idx | Score |\n`;
  md += `|---|------|--------|-------|-----|--------|-----------|----------------|-------|\n`;
  for (const [i, r] of rows.entries()) {
    const n = tier.slice[0] + i + 1;
    md += `| ${n} | ${r.name} | ${r.county} | ${r.state} | ${r.pop.toLocaleString()} | ${r.hispanic_pct}% | ${r.hispanicPop.toLocaleString()} | ${r.contractor_index} | **${r.score}** |\n`;
  }
}

md += `

## How to promote a town

1. Move its row from \`src/data/town_pipeline.json\` into \`src/data/towns.json\`.
2. Fill in the fields the pipeline file doesn't carry: \`name_es\`, \`county_es\`,
   \`zip_list\`, \`lat\`, \`lng\`, \`nearby_slugs\`, \`local_notes_es\`, \`local_notes_en\`.
3. Write the four \`angles\` entries — one per service, in both languages. **This is
   the step that decides whether the pages rank.** An angle is a specific,
   checkable local fact: which county the crews commute to, what the housing
   stock is, what the landlords require, which regulator applies. If you cannot
   write four distinct angles for a town, it is not ready to promote.
4. \`npm run generate:towns\` to emit the MDX, then \`npm run build && npm run similarity\`.
5. If any pair scores above 0.70, the angles are too generic. Rewrite them.

## Notes on specific entries

- **Lakewood** ranks high on contractor density but its Hispanic share is lower
  than the Hudson/Passaic cluster; the construction volume there is real but the
  Spanish-language search demand needs checking before you commit the pages.
- **East Orange** and **Irvington** score on population, not Hispanic share. They
  are better candidates for English-first pages than Spanish-first ones.
- The **Bronx** neighborhoods are NY jurisdiction: workers' comp, DBL and PFL all
  differ from NJ. Their \`angles\` must not reuse NJ framing.
- NYC neighborhood "towns" are not municipalities. Decide deliberately whether to
  target the neighborhood name (what people search) or the borough (what maps to
  a real administrative area) — the current seed data does both, which is worth
  revisiting.
`;

await writeFile('CONTENT_QUEUE.md', md);
console.log(`CONTENT_QUEUE.md written: ${ranked.length} towns, ${ranked.length * pagesPerTown} pages.`);
console.log(`Top 5: ${ranked.slice(0, 5).map((r) => `${r.name} (${r.score})`).join(', ')}`);
